blockchain/urls.py
from django.urls import path

from . import views

app_name = 'blockchain'

urlpatterns = [
    path('detail/<slug:slug>/', views.detail, name='detail'),
    # path('detail/<int:id>/<str:exchenger>/<slug:slug>/', views.detail, name='detail'),
    path('create_portfolio/<int:blockchain_id>/', views.create_blockchain_portfolio,
         name='create_blockchain_portfolio'),
    path('change_portfolio/<int:blockchain_id>/', views.change_blockchain_portfolio,
         name='change_blockchain_portfolio'),
    path('delete_portfolio/<int:blockchain_id>/', views.delete_blockchain_portfolio,
         name='delete_blockchain_portfolio'),
    path('data/<int:blockchain_id>/', views.get_blockchain_data, name='get_blockchain_data'),
    # path('all-data/<int:user_id>/', views.get_all_data, name='get_all_data'),
    path('blockchain_data_pdf/<int:blockchain_id>/', views.get_blockchain_data_pdf, name='get_blockchain_data_pdf'),
]

cmc/urls.py
from django.urls import path

from . import views

app_name = 'cmc'

urlpatterns = [
    path('detail/<slug:slug>/', views.detail, name='crypto_detail'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from cmc.views import index
from exchanger.views import send_XLSX_by_email, send_PDF_by_email

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),

    path('exchanger/', include('exchanger.urls', namespace='exchanger')),
    path('blockchain/', include('blockchain.urls', namespace='blockchain')),

    path('cmc/', include('cmc.urls', namespace='cmc')),

    path('send_XLSX_by_email/<str:portfolio>/', send_XLSX_by_email, name='send_XLSX_by_email'),
    path('send_XLSX_by_email/<path:path_to_file>/', send_XLSX_by_email, name='send_XLSX_by_email'),
    path('send_PDF_by_email/<int:user_id>/', send_PDF_by_email, name='send_PDF_by_email'),
    path('send_PDF_by_email/<int:user_id>/<str:portfolio>/', send_PDF_by_email, name='send_PDF_by_email'),

    path('', index, name='index'),
    re_path('', include('social_django.urls', namespace='social'))

]

from account.api.urls import urlpatterns as users_urlpatterns
from blockchain.api.urls import urlpatterns as blockchain_urlpatterns
from exchanger.api.urls import urlpatterns as exchanger_urlpatterns

urlpatterns += [*users_urlpatterns, *blockchain_urlpatterns, *exchanger_urlpatterns]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

exchanger/api/urls.py
from django.urls import path, include
from rest_framework import routers


from exchanger.api.views import ExchangerViewSet, ExPortfolioViewSet
from exchanger.api.views_bot import ExchangerPortfolioForBot, ExchangerDataForBot, AllDataForBot

router = routers.DefaultRouter()
router.register(r'api/exchanger', ExchangerViewSet)
router.register(r'api/exportfolio', ExPortfolioViewSet)


from exchanger.api.views import ExchangerData, AllData

urlpatterns = [
    path('api/exchanger/data/<int:exchanger_id>/', ExchangerData.as_view(), name='exchanger-data'),
    path('api/user/data/all/', AllData.as_view(), name='all-data'),


    path('api/bot/exchanger-portfolio/', ExchangerPortfolioForBot.as_view(),
         name='exchanger-bot'),
    path('api/bot/exchanger-portfolio-data/', ExchangerDataForBot.as_view(),
         name='exchanger-data-bot'),

    path('api/bot/data-all/', AllDataForBot.as_view(),
         name='all-data-bot'),

    path('', include(router.urls)),
    ]

exchanger/urls.py
from django.urls import path

from . import views

app_name = 'exchanger'

urlpatterns = [
    path('detail/<slug:slug>/', views.detail, name='detail'),
    path('detail/<int:id>/<str:exchenger>/<slug:slug>/', views.detail, name='detail'),
    path('create_portfolio/<int:exchanger_id>/', views.create_portfolio, name='create_portfolio'),
    path('change_portfolio/<int:exchanger_id>/', views.change_portfolio, name='change_portfolio'),
    path('delete_portfolio/<int:exchanger_id>/', views.delete_portfolio, name='delete_portfolio'),
    path('data/<int:exchanger_id>/', views.get_exchanger_data, name='get_exchanger_data'),
    path('all-data/<int:user_id>/', views.get_all_data, name='get_all_data'),
    path('all_data_pdf/<int:user_id>/', views.get_all_data_pdf, name='get_all_data_pdf'),
    path('exchanger_data_pdf/<int:exchanger_id>/', views.get_exchanger_data_pdf, name='get_exchanger_data_pdf'),
    path('', views.exchangers, name='exchangers'),

]

exchanger/api/views.py
from django.shortcuts import get_object_or_404
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets
from rest_framework.authentication import SessionAuthentication
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.permissions import IsAdminUser
from rest_framework.views import APIView
from rest_framework.response import Response

from account.api.permissions import IsAuthenticatedAndOwnerOrIsStaff, IsAuthenticatedAndOwner
from exchanger.models import Exchanger, ExPortfolio
from exchanger.api.serializers import ExchangerSerializer, ExPortfolioSerializer
from exchanger.cache import check_caches_exchanger_data, check_cache_user_portfolios_data


class ExchangerViewSet(viewsets.ModelViewSet):
    queryset = Exchanger.objects.all()
    serializer_class = ExchangerSerializer
    permission_classes = [IsAdminUser]

    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ['name', 'is_active']
    search_fields = ['name', 'is_active']
    ordering_fields = ['id', 'name']


class ExPortfolioViewSet(viewsets.ModelViewSet):
    queryset = ExPortfolio.objects.all()
    serializer_class = ExPortfolioSerializer
    permission_classes = [IsAuthenticatedAndOwnerOrIsStaff]

    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ['owner__username', 'exchanger__name']
    search_fields = ['owner__username', 'exchanger__name']
    ordering_fields = ['owner', 'exchanger__name']


class ExchangerData(APIView):
    # authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticatedAndOwner]

    def get(self, request, exchanger_id, format=None):
        portfolio = get_object_or_404(ExPortfolio,
                                      owner=self.request.user.id,
                                      exchanger=exchanger_id)
        response_exchanger, total_sum = check_caches_exchanger_data(portfolio)

        return Response({portfolio.exchanger.name: [response_exchanger, total_sum]})


class AllData(APIView):
    # authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticatedAndOwner]

    def get(self, request, format=None):
        user_portfolios_data = check_cache_user_portfolios_data(self.request.user.id)

        return Response({self.request.user.username: user_portfolios_data})

exchanger/views.py
import os

import pdfkit
from django.conf import settings

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.template.loader import render_to_string

from local_settings import path_wkhtmltopdf_win, path_wkhtmltopdf_lin, ALL_PORTFOLIOS
from .cache import (check_cache_user_portfolios_data,
                    check_caches_exchanger_data,
                    delete_caches_exchanger_data,
                    delete_cache_user_portfolios_data)
from .models import Exchanger, ExPortfolio
from .forms import ExPortfolioForm

from exchanger.tasks import (save_portfolio_to_xlsx_file, save_all_to_xlsx_file, 
                             sending_XLSX_by_email, sending_PDF_by_email)

from blockchain.models import Blockchain


@login_required
def exchangers(request):
    exchangers_list = Exchanger.objects.filter(is_active=True)
    blockchains_list = Blockchain.objects.filter(is_active=True)
    return render(request, 'exchanger/exchangers.html', {'exchangers': exchangers_list,
                                                         'blockchains_list': blockchains_list})


@login_required
def create_portfolio(request, exchanger_id):
    exchanger = get_object_or_404(Exchanger,
                                  id=exchanger_id)
    form = ExPortfolioForm()
    if request.method == 'POST':
        form = ExPortfolioForm(data=request.POST)
        if form.is_valid():
            portfolio = form.save(commit=False)
            portfolio.owner = request.user
            portfolio.exchanger = exchanger
            portfolio.save()

            delete_caches_exchanger_data(portfolio)
            delete_cache_user_portfolios_data(portfolio.owner.id)

            messages.success(request, 'Portfolio created successfully')
            return redirect('exchanger:exchangers')
        else:
            messages.error(request, 'Error created your portfolio')

    return render(request, 'exchanger/add_portfolio.html', {'exchanger': exchanger,
                                                            'form': form,
                                                            'button': 'Create'})


@login_required
def change_portfolio(request, exchanger_id):
    exchanger = get_object_or_404(Exchanger,
                                  id=exchanger_id)
    portfolio = get_object_or_404(ExPortfolio,
                                  owner=request.user,
                                  exchanger=exchanger_id)
    form = ExPortfolioForm(instance=portfolio)
    if request.method == 'POST':
        form = ExPortfolioForm(data=request.POST)
        if form.is_valid():
            portfolio.api_key = form.cleaned_data.get('api_key')
            portfolio.api_secret = form.cleaned_data.get('api_secret')
            portfolio.password = form.cleaned_data.get('password')
            portfolio.comments = form.cleaned_data.get('comments')
            portfolio.save()

            delete_caches_exchanger_data(portfolio)
            delete_cache_user_portfolios_data(portfolio.owner.id)

            messages.success(request, 'Portfolio changed successfully')
            return redirect('exchanger:exchangers')
        else:
            messages.error(request, 'Error changed your portfolio')

    return render(request, 'exchanger/add_portfolio.html', {'exchanger': exchanger,
                                                            'form': form,
                                                            'button': 'Change'})


@login_required
def delete_portfolio(request, exchanger_id):
    exchanger = Exchanger.objects.get(id=exchanger_id)
    portfolio = get_object_or_404(ExPortfolio,
                                  owner=request.user,
                                  exchanger=exchanger_id)

    form = ExPortfolioForm(instance=portfolio)
    if request.GET.get('yes') == 'yes':
        portfolio.delete()
        messages.success(request, f'Portfolio {portfolio.exchanger} deleted successfully')

        delete_caches_exchanger_data(portfolio)
        delete_cache_user_portfolios_data(portfolio.owner.id)

        return redirect('exchanger:exchangers')

    return render(request, 'exchanger/delete_portfolio.html', {'exchanger': exchanger,
                                                               'form': form})


@login_required
def get_exchanger_data(request, exchanger_id):
    portfolio = get_object_or_404(ExPortfolio,
                                  owner=request.user,
                                  exchanger=exchanger_id)
    response_exchanger, total_sum = check_caches_exchanger_data(portfolio)

    portfolio_name = portfolio.exchanger.name
    save_portfolio_to_xlsx_file.delay(request.user.id,
                                      [{portfolio_name: response_exchanger}],
                                      portfolio_name)

    if 'error' in response_exchanger[0]:
        return render(request, 'exchanger/data_portfolio.html', {'portfolio': portfolio,
                                                                 'data': response_exchanger,
                                                                 'total_sum': 0,
                                                                 })

    return render(request, 'exchanger/data_portfolio.html', {'portfolio': portfolio,
                                                             'data': response_exchanger,
                                                             'total_sum': total_sum,
                                                             })


@login_required
def get_exchanger_data_pdf(request, exchanger_id):
    """
    https://www.geeksforgeeks.org/python-convert-html-pdf/
    https://pythoncircle.com/post/470/generating-and-returning-pdf-as-response-in-django/
    """
    portfolio = get_object_or_404(ExPortfolio,
                                  owner=request.user,
                                  exchanger=exchanger_id)
    response_exchanger, total_sum = check_caches_exchanger_data(portfolio)

    pdf = get_exchanger_pdf(portfolio, response_exchanger, total_sum)
    response = HttpResponse(pdf, content_type='application/pdf')
    response['Content-Disposition'] = f'filename=PDF_{portfolio.exchanger.name}' \
                                      f'_{portfolio.owner.username.capitalize()}.pdf'
    return response


def get_exchanger_pdf(portfolio, user_portfolio_data, total_sum):
    html = render_to_string('exchanger/pdf_exchanger.html',
                            {'portfolio': portfolio,
                             'user_portfolio_data': user_portfolio_data,
                             'total_sum': total_sum})
    path_wkhtmltopdf = get_path_to_wkhtmltopdf()
    config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)
    pdf_settings = {
        'encoding': "UTF-8",
        'no-outline': None
    }
    pdf = pdfkit.from_string(input=html,
                             css=settings.STATIC_ROOT / 'cmc/css/pdf.css',
                             configuration=config,
                             options=pdf_settings)
    return pdf


@login_required
def get_all_data(request, user_id):
    user_portfolios_data = check_cache_user_portfolios_data(user_id)

    save_all_to_xlsx_file.delay(request.user.id, user_portfolios_data, portfolio_name=ALL_PORTFOLIOS)

    return render(request, 'exchanger/data_all_portfolios.html',
                  {'user_portfolios_data': user_portfolios_data})


@login_required
def detail(request, slug):
    return render(request, 'exchanger/detail.html')


@login_required
def get_all_data_pdf(request, user_id):
    """
    https://www.geeksforgeeks.org/python-convert-html-pdf/
    https://pythoncircle.com/post/470/generating-and-returning-pdf-as-response-in-django/
    """
    user = get_object_or_404(User, id=user_id)
    user_portfolios_data = check_cache_user_portfolios_data(user_id)

    pdf = get_pdf(user_portfolios_data)
    response = HttpResponse(pdf, content_type='application/pdf')
    response['Content-Disposition'] = f'filename=PDF_portfolio_User_{user.username.capitalize()}.pdf'
    return response


def get_pdf(user_portfolios_data):
    html = render_to_string('exchanger/pdf.html', {'user_portfolios_data': user_portfolios_data})
    path_wkhtmltopdf = get_path_to_wkhtmltopdf()
    config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)
    pdf_settings = {
        'encoding': "UTF-8",
        'no-outline': None
    }
    pdf = pdfkit.from_string(input=html,
                             css=settings.STATIC_ROOT / 'cmc/css/pdf.css',
                             configuration=config,
                             options=pdf_settings)
    return pdf


def get_path_to_wkhtmltopdf():
    path_wkhtmltopdf = path_wkhtmltopdf_win
    if os.path.isfile(path_wkhtmltopdf):
        return path_wkhtmltopdf
    return path_wkhtmltopdf_lin


@login_required
def send_XLSX_by_email(request, path_to_file=None, portfolio=ALL_PORTFOLIOS):
    if portfolio:
        xlsx_dir = settings.MEDIA_URL + 'xlsx_files/' + f'{request.user.id}_{request.user.username.lower()}/'
        filename = f'{request.user.id}_{request.user.username.lower()}_{portfolio}.xlsx'
        path_to_file = xlsx_dir + filename

    sending_XLSX_by_email.delay(request.user.id, path_to_file, portfolio)
    messages.success(request, f'Portfolios {portfolio} were send to your email.')
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def send_PDF_by_email(request, user_id=None, portfolio=ALL_PORTFOLIOS):
    xlsx_dir = settings.MEDIA_URL + 'xlsx_files/' + f'{request.user.id}_{request.user.username.lower()}/'
    filename = f'{request.user.id}_{request.user.username.lower()}_{ALL_PORTFOLIOS}.pdf'
    path_to_file = xlsx_dir + filename
    if portfolio:
        filename = f'{request.user.id}_{request.user.username.lower()}_{portfolio}.pdf'

exchanger/templates/exchanger/add_portfolio.html
{% extends "base_index.html" %}

{% load thumbnail %}

{% block bootstrap5_title %}Exchangers{% endblock %}

{% block bootstrap5_extra_head %}
{% endblock bootstrap5_extra_head %}


{% block main_content %}
    <div class="text-center">
        <h1>Exchanger - {{ exchanger.name }}</h1>
        <p>
            Here you can ...
        </p>
    </div>

    <div class="container col-md-6 text-center">
        <form method="post">
            <table class="table table-borderless">
                {{ form.as_table }}
            </table>
            {% csrf_token %}
            <p>
                <input type="submit" value="{% if button == 'Create' %}Create{% elif button == 'Change' %}Change{% endif %}"
                      class="btn btn-success">
            </p>
        </form>
    </div>


{% endblock main_content %}


{% block sidebar %}
{% endblock sidebar %}

exchanger/templates/exchanger/data_all_portfolios.html
{% extends "base_index.html" %}

{% load exchanger_tags %}
{% load thumbnail %}

{% block bootstrap5_title %}Exchangers{% endblock %}

{% block bootstrap5_extra_head %}
{% endblock bootstrap5_extra_head %}


{% block main_content %}
    <div class="text-center">
        <h1>Users portfolios data.</h1>
        <p>
            Here you ...
        </p>
    </div>

    <div class="container text-center">
        {% for portfolio in user_portfolios_data %}

            {% for name, portfolio_data in portfolio.items %}
                <h3>Users portfolios {{ name|upper }}</h3>

                <table class="table table-striped align-middle" id="">
                    <thead class="table-primary">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col" class="text-center">Coin</th>
                        <th scope="col" class="text-center">Balance</th>
                        <th scope="col" class="text-center">Data</th>
                        <th scope="col" class="text-center">CMC id</th>
                        <th scope="col" class="text-center">Name</th>
                        <th scope="col" class="text-center">Price</th>
                        <th scope="col" class="text-center">Total:
                            <span class="text-center h4">{% get_sum_portfolio portfolio_data %}</span>
                        </th>
                    </tr>
                    </thead>

                    {% for data in portfolio_data %}
                        <tbody>
                        <tr>
                        {% if data.error %}
                            <td colspan="8">{{ data.error }}</td>
                        {% else %}
                            <td>{{ forloop.counter }}</td>
                            <td>{{ data.coin }}</td>
                            <td>{{ data.bal }}</td>
                            <td>{{ data.data }}</td>
                            <td>{{ data.id }}</td>
                            <td>{{ data.name }}</td>
                            <td>{{ data.price }}</td>
                            <td>{{ data.total }}</td>
                        {% endif %}
                        </tr>
                        </tbody>
                    {% endfor %}
                </table>

            {% endfor %}

        {% endfor %}


    </div>


    {#    {% include 'cmc/cmc/include/_paginate.html' with page=data %}#}

{% endblock main_content %}


{% block sidebar %}
{% endblock sidebar %}

exchanger/templates/exchanger/delete_portfolio.html
{% extends "base_index.html" %}

{% load thumbnail %}

{% block bootstrap5_title %}Exchangers{% endblock %}

{% block bootstrap5_extra_head %}
{% endblock bootstrap5_extra_head %}


{% block main_content %}
    <div class="container col-md-6 text-center">
        <h1>Exchanger - {{ exchanger.name }}</h1>
        <div class="container">
            <table class="table table-striped align-middle" id="">
                <thead class="table-primary">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col" class="text-center">Exchangers</th>
                    <th scope="col" class="text-center">Logo</th>
                </tr>
                </thead>

                <tbody>
                <tr>
                    <td>1.</td>
                    <td><a href="#" class="link">
                        {{ exchanger.name }}</a>
                    </td>
                    <td>
                        <img src="{% thumbnail exchanger.logo 120x120 %}">
                    </td>
                </tr>

                </tbody>
            </table>

            <h3 class="text-danger">
                Are you sure to delete portfolio "OLX" "{{ exchanger.name }}"
            </h3>
        </div>
        <p>
            <a href="{% url 'exchanger:delete_portfolio' exchanger.id %}?yes=yes">
                <input type="button" value="Delete" class="btn btn-danger"/>
            </a>
        </p>
    </div>


{% endblock main_content %}


{% block sidebar %}
{% endblock sidebar %}

exchanger/templates/exchanger/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <title>Exchanger detail</title>
</body>
</html>

exchanger/templates/exchanger/exchangers.html
{% extends "base_index.html" %}

{% load exchanger_tags %}
{% load blockchain_tags %}

{% load thumbnail %}

{% block bootstrap5_title %}Exchangers{% endblock %}

{% block bootstrap5_extra_head %}
{% endblock bootstrap5_extra_head %}


{% block main_content %}
    <div class="text-center">
        <h1>Exchangers.</h1>
        <p>
            Here you can add data for exchangers which using.
        </p>
    </div>


    <div class="container-fluid text-center">
        <div class="row">
            <div class="col">
                <h3>Please choose exchanger:</h3>
                {% if exchangers %}
                    <div class="container">
                    <table class="table table-striped align-middle" id="">
                        <thead class="table-primary">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col" class="text-center">Exchangers</th>
                            <th scope="col" class="text-center">Logo</th>
                            <th scope="col" class="text-center">Create</th>
                            <th scope="col" class="text-center">Delete</th>
                            <th scope="col" class="text-center">Change</th>
                        </tr>
                        </thead>

                        <tbody>

                        {% for exchanger in exchangers %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="{{ exchanger.website }}" class="link" target="_blank" >
                                    {{ exchanger.name }}</a>
                                </td>
                                <td>
                                    <img src="{% thumbnail exchanger.logo 120x120 %}">
                                </td>

                                {% if exchanger in exchanger_portfolios %}
                                    <td>
                                        <button type="button" class="btn btn-outline-success disabled">
                                            <a href="{% url "exchanger:create_portfolio" exchanger.id %}" class="link">
                                                Create portfolio</a>
                                        </button>

                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-outline-info">
                                            <a href="{% url "exchanger:change_portfolio" exchanger.id %}" class="link">
                                                Change portfolio</a>
                                        </button>
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-outline-danger">
                                            <a href="{% url "exchanger:delete_portfolio" exchanger.id %}" class="link">
                                                Delete portfolio</a>
                                        </button>
                                    </td>
                                {% else %}
                                    <td>
                                        <button type="button" class="btn btn-outline-success">
                                            <a href="{% url "exchanger:create_portfolio" exchanger.id %}" class="link">
                                                Create portfolio</a>
                                        </button>

                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-outline-info" disabled>
                                            <a href="{% url "exchanger:change_portfolio" exchanger.id %}" class="link">
                                                Change portfolio</a>
                                        </button>
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-outline-danger disabled">
                                            <a href="{% url "exchanger:delete_portfolio" exchanger.id %}" class="link">
                                                Delete portfolio</a>
                                        </button>
                                    </td>
                                {% endif %}

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h1>Exchangers not found!</h1>
                {% endif %}
                </div>
            </div>

            <div class="col">
                <h3>Please choose exchanger:</h3>
                {% if blockchains_list %}
                    <div class="container">
                    <table class="table table-striped align-middle" id="">
                        <thead class="table-primary">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col" class="text-center">Exchangers</th>
                            <th scope="col" class="text-center">Logo</th>
                            <th scope="col" class="text-center">Create</th>
                            <th scope="col" class="text-center">Delete</th>
                            <th scope="col" class="text-center">Change</th>
                        </tr>
                        </thead>

                        <tbody>

                        {% for blockchain in blockchains_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>
                                    <a href="{{ blockchain.website }}" class="link" target="_blank" >
                                    {{ blockchain.name }}</a>
                                </td>
                                <td>

                                    <img src="{% thumbnail blockchain.logo 120x120 %}">
                                </td>

                                {% if blockchain in blockchain_portfolios %}
                                    <td>
                                        <button type="button" class="btn btn-outline-success disabled">
                                            <a href="{% url "blockchain:create_blockchain_portfolio" blockchain.id %}" class="link">
                                                Create portfolio</a>
                                        </button>

                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-outline-info">
                                            <a href="{% url "blockchain:change_blockchain_portfolio" blockchain.id %}" class="link">
                                                Change portfolio</a>
                                        </button>
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-outline-danger">
                                            <a href="{% url "blockchain:delete_blockchain_portfolio" blockchain.id %}" class="link">
                                                Delete portfolio</a>
                                        </button>
                                    </td>
                                {% else %}
                                    <td>
                                        <button type="button" class="btn btn-outline-success">
                                            <a href="{% url "blockchain:create_blockchain_portfolio" blockchain.id %}" class="link">
                                                Create portfolio</a>
                                        </button>

                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-outline-info" disabled>
                                            <a href="{% url "blockchain:change_blockchain_portfolio" blockchain.id %}" class="link">
                                                Change portfolio</a>
                                        </button>
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-outline-danger disabled">
                                            <a href="{% url "blockchain:delete_blockchain_portfolio" blockchain.id %}" class="link">
                                                Delete portfolio</a>
                                        </button>
                                    </td>
                                {% endif %}

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h1>Exchangers not found!</h1>
                {% endif %}
                </div>
            </div>
        </div>
    </div>


{% endblock main_content %}


{% block sidebar %}
{% endblock sidebar %}