blockchain/urls.py
from django.urls import path

from . import views

app_name = 'blockchain'

urlpatterns = [
    path('detail/<slug:slug>/', views.detail, name='detail'),
    # path('detail/<int:id>/<str:exchenger>/<slug:slug>/', views.detail, name='detail'),
    path('create_portfolio/<int:blockchain_id>/', views.create_blockchain_portfolio,
         name='create_blockchain_portfolio'),
    path('change_portfolio/<int:blockchain_id>/', views.change_blockchain_portfolio,
         name='change_blockchain_portfolio'),
    path('delete_portfolio/<int:blockchain_id>/', views.delete_blockchain_portfolio,
         name='delete_blockchain_portfolio'),
    path('data/<int:blockchain_id>/', views.get_blockchain_data, name='get_blockchain_data'),
    # path('all-data/<int:user_id>/', views.get_all_data, name='get_all_data'),
    path('blockchain_data_pdf/<int:blockchain_id>/', views.get_blockchain_data_pdf, name='get_blockchain_data_pdf'),
]

cmc/urls.py
from django.urls import path

from . import views

app_name = 'cmc'

urlpatterns = [
    path('detail/<slug:slug>/', views.detail, name='crypto_detail'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from cmc.views import index
from exchanger.views import send_XLSX_by_email, send_PDF_by_email

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),

    path('exchanger/', include('exchanger.urls', namespace='exchanger')),
    path('blockchain/', include('blockchain.urls', namespace='blockchain')),

    path('cmc/', include('cmc.urls', namespace='cmc')),

    path('send_XLSX_by_email/<str:portfolio>/', send_XLSX_by_email, name='send_XLSX_by_email'),
    path('send_XLSX_by_email/<path:path_to_file>/', send_XLSX_by_email, name='send_XLSX_by_email'),
    path('send_PDF_by_email/<int:user_id>/', send_PDF_by_email, name='send_PDF_by_email'),
    path('send_PDF_by_email/<int:user_id>/<str:portfolio>/', send_PDF_by_email, name='send_PDF_by_email'),

    path('', index, name='index'),
    re_path('', include('social_django.urls', namespace='social'))

]

from account.api.urls import urlpatterns as users_urlpatterns
from blockchain.api.urls import urlpatterns as blockchain_urlpatterns
from exchanger.api.urls import urlpatterns as exchanger_urlpatterns

urlpatterns += [*users_urlpatterns, *blockchain_urlpatterns, *exchanger_urlpatterns]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

exchanger/urls.py
from django.urls import path

from . import views

app_name = 'exchanger'

urlpatterns = [
    path('detail/<slug:slug>/', views.detail, name='detail'),
    path('detail/<int:id>/<str:exchenger>/<slug:slug>/', views.detail, name='detail'),
    path('create_portfolio/<int:exchanger_id>/', views.create_portfolio, name='create_portfolio'),
    path('change_portfolio/<int:exchanger_id>/', views.change_portfolio, name='change_portfolio'),
    path('delete_portfolio/<int:exchanger_id>/', views.delete_portfolio, name='delete_portfolio'),
    path('data/<int:exchanger_id>/', views.get_exchanger_data, name='get_exchanger_data'),
    path('all-data/<int:user_id>/', views.get_all_data, name='get_all_data'),
    path('all_data_pdf/<int:user_id>/', views.get_all_data_pdf, name='get_all_data_pdf'),
    path('exchanger_data_pdf/<int:exchanger_id>/', views.get_exchanger_data_pdf, name='get_exchanger_data_pdf'),
    path('', views.exchangers, name='exchangers'),

]

cmc/models.py
from django.core.validators import validate_image_file_extension
from django.db import models
from django.urls import reverse

from passlib.hash import pbkdf2_sha256


class Cryptocurrency(models.Model):
    symbol = models.CharField(max_length=255, verbose_name='Symbol')
    name = models.CharField(max_length=255, verbose_name='Name')
    slug = models.SlugField(max_length=250, unique=True)
    website = models.URLField(max_length=200,
                              verbose_name='Site',
                              blank=True,
                              )

    contract = models.CharField(max_length=255, verbose_name='Contract', blank=True)
    description = models.TextField(verbose_name='Description', blank=True)
    logo = models.ImageField(upload_to=f'cryptocurrency/%Y/%m/%d/',
                             blank=True,
                             validators=[validate_image_file_extension])

    class Meta:
        indexes = [
            models.Index(fields=['symbol']),
        ]
        ordering = ['name']

    def __str__(self):
        return f'{self.name}. {self.symbol}'

    def get_absolute_url(self):
        return reverse('cmc:crypto_detail',
                       args=[self.slug])


class TelegramBot(models.Model):
    bot_name = models.CharField(max_length=255,
                                unique=True,
                                verbose_name='bot_name',
                                help_text="Bot name from telegram bot settings.")
    username = models.CharField(max_length=255,
                                unique=True,
                                verbose_name='username',
                                help_text="Bot username from telegram bot settings.", )
    bot_token = models.CharField(max_length=255,
                                 unique=True,
                                 verbose_name='bot_token',
                                 help_text="Bot token from telegram bot settings.", )
    chat_id = models.IntegerField(unique=True,
                                  verbose_name='chat_id',
                                  help_text="Bot id.", )
    hash_password = models.CharField(max_length=255,
                                     unique=True, )

    class Meta:
        indexes = [
            models.Index(fields=['bot_name']),
        ]
        ordering = ['bot_name']

    def __str__(self):
        return f'{self.bot_name}.'

    def save(self, *args, **kwargs):
        self.hash_password = pbkdf2_sha256.hash(f'{self.bot_name} + {self.username} + {self.chat_id}')
        super().save(*args, **kwargs)


def pwd_verify(*args, **kwargs):
    bot_name, username, chat_id = args
    hash_password = TelegramBot.objects.first().hash_password
    return bool(pbkdf2_sha256.verify(f'{bot_name} + {username} + {chat_id}',
                                     hash_password))

cmc/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, HttpResponse, get_object_or_404

from django import forms

from cmc.models import Cryptocurrency
from exchanger.handlers import get_paginator

PAGINATOR_QTY = 10


def index(request):

    cryptocurrencies_list = Cryptocurrency.objects.all().order_by('id')[:154]
    cryptocurrencies, page_range = get_paginator(request, cryptocurrencies_list)
    return render(request,
                  'cmc/cmc/index.html',
                  {'cryptocurrencies': cryptocurrencies,
                   'page_range': page_range}
                  )


def detail(request, slug):
    crypto = get_object_or_404(Cryptocurrency,
                               slug=slug
                               )

    return render(request, 'cmc/cmc/detail.html',
                  {'crypto': crypto}
                  )

cmc/templates/include/_go_back.html
<div class="container">
    <form>
        <input class="btn btn-secondary" type="button" value="&laquo; Go back!" onclick="history.back()">
    </form>
</div>

cmc/templates/include/_message.html
{% for message in messages %}
    <div class="container text-center col-md-4">
        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        {{ message }}
            <button type="button" class="btn-close" aria-label="Close"></button>
        </div>
    </div>
{% endfor %}

cmc/templates/include/footer.html
{% block bootstrap5_extra_head %}
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/8233c1c233.js" crossorigin="anonymous"></script>
{% endblock %}

{#<div CLASS="b-example-divider"></div>#}

<div class="container-fluid footer_container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top border-bottom">
        <div class="col-md-4 d-flex align-items-center">
            <a class="text-secondary" href="/"><i class="fa-brands fa-bootstrap fa-2xl"></i></a>
            <span class="mb-3 mb-md-0 text-secondary">Copyright © {% now "Y" %} All rights reserved</span>
        </div>

        <ul class="nav col-md-4 justify-content-center d-flex">
            <li class="nav-item"><a href="/" class="nav-link px-2 text-secondary">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-secondary">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-secondary">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-secondary">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-secondary">About</a></li>
        </ul>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-secondary" href="#"><i class="fa-brands fa-twitter fa-xl"></i></a></li>
            <li class="ms-3"><a class="text-secondary" href="#"><i class="fa-brands fa-facebook fa-xl"></i></a></li>
            <li class="ms-3"><a class="text-secondary" href="#"><i class="fa-brands fa-dropbox fa-xl"></i></a></li>
            <li class="ms-3"><a class="text-secondary" href="#"><i class="fa-brands fa-flickr fa-xl"></i></a></li>
            <li class="ms-3"><a class="text-secondary" href="#"><i class="fa-brands fa-github fa-xl"></i></a></li>
            <li class="ms-3"><a class="text-secondary" href="#"><i class="fa-brands fa-linkedin fa-xl"></i></a></li>
            <li class="ms-3"><a class="text-secondary" href="#"><i class="fa-brands fa-instagram fa-xl"></i></a></li>
            <li class="ms-3"><a class="text-secondary" href="#"><i class="fa-brands fa-google-plus fa-xl"></i></a></li>
        </ul>
    </footer>
</div>

cmc/templates/include/navbar.html
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" aria-label="Fourth navbar example">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Crypto balances |</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04"
              aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample04">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
{#          <li class="nav-item">#}
{#            <a class="nav-link" href="#">Link</a>#}
{#          </li>#}
{#          <li class="nav-item">#}
{#            <a class="nav-link disabled">Disabled</a>#}
{#          </li>#}
{#          <li class="nav-item dropdown">#}
{#            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>#}
{#            <ul class="dropdown-menu">#}
{#              <li><a class="dropdown-item" href="#">Action</a></li>#}
{#              <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#              <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#            </ul>#}
{#          </li>#}
        </ul>

        {% include 'include/user.html' %}

        <form role="search">
          <input class="form-control" type="search" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>

cmc/templates/include/user.html
<ul class="navbar-nav navbar-right">
    {% if not user.is_authenticated %}
        <li>
            <a class="action nav-link" href="{% url "login" %}">
                <i class="fa-solid fa-right-to-bracket"></i> Login</a></li>
        <li>

            <a class="action nav-link" href="{% url "register" %}">
                <i class="fa-solid fa-user-plus"></i> Sign up</a></li>
    {% endif %}

    {% if user.is_authenticated %}

        <li class='nav-link'>
            <a class="dropdown-item" href="{% url "exchanger:exchangers" %}">
                Hello, {% if user.first_name %} {{ user.first_name }}
            {% else %} {{ user.username }}
            {% endif %}
            </a>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#"
               data-bs-toggle="dropdown" aria-expanded="false">Exchangers
            </a>
{#            <ul class="dropdown-menu">#}
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

                {% if exchanger_portfolios %}
                    {% for exchanger_portfolio in exchanger_portfolios %}
                        <li>
                            <a href="#"
                               class="dropdown-item link">{{ exchanger_portfolio }} &raquo
                            </a>
                                <ul class="dropdown-menu dropdown-submenu">
                                    <li>
                                        <a class="dropdown-item link"
                                           href="{% url "exchanger:get_exchanger_data" exchanger_portfolio.id %}">Data</a>
                                    </li>
                                    <hr class="dropdown-divider">
                                    <li>
                                        <a class="dropdown-item link" href="{% url "exchanger:change_portfolio" exchanger_portfolio.id %}">Change</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item link" href="{% url "exchanger:delete_portfolio" exchanger_portfolio.id %}">Delete</a>
                                    </li>
                                </ul>
                        </li>


                    {% endfor %}
                {% else %}
                    <p>You did not create yet.</p>
                {% endif %}

                <hr class="dropdown-divider">
                <li><a class="dropdown-item link" href="{% url "exchanger:exchangers" %}">All</a></li>

            </ul>
        </li>



        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">BlockChains</a>
            <ul class="dropdown-menu">

                {% if blockchain_portfolios %}
                    {% for blockchain_portfolio in blockchain_portfolios %}
                        <li>
                            <a href="#"
                               class="dropdown-item link">{{ blockchain_portfolio }} &raquo
                            </a>
                                <ul class="dropdown-menu dropdown-submenu">
                                    <li>
                                        <a class="dropdown-item link"
                                           href="{% url "blockchain:get_blockchain_data" blockchain_portfolio.id %}">Data</a>
                                    </li>
                                    <hr class="dropdown-divider">
                                    <li>
                                        <a class="dropdown-item link" href="{% url "blockchain:change_blockchain_portfolio" blockchain_portfolio.id %}">Change</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item link" href="{% url "blockchain:delete_blockchain_portfolio" blockchain_portfolio.id %}">Delete</a>
                                    </li>
                                </ul>
                        </li>

                    {% endfor %}
                {% else %}
                    <p>You did not create yet.</p>
                {% endif %}

                <hr class="dropdown-divider">
                <li><a class="dropdown-item link" href="{% url "exchanger:exchangers" %}">All</a></li>

            </ul>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Settings</a>
            <ul class="dropdown-menu">
                <li>
                    <a class="dropdown-item link" href="{% url "edit" %}">Edit_detail</a>
                    {#                    <a class="dropdown-item" href="#">1111111</a>#}
                </li>
            </ul>
        </li>

        <li>
            <a class='action  nav-link' href="{% url "logout" %}">
                <i class="fa-solid fa-right-from-bracket"></i> Logout</a></li>
    {% endif %}
</ul>