blockchain/urls.py
from django.urls import path

from . import views

app_name = 'blockchain'

urlpatterns = [
    path('detail/<slug:slug>/', views.detail, name='detail'),
    # path('detail/<int:id>/<str:exchenger>/<slug:slug>/', views.detail, name='detail'),
    path('create_portfolio/<int:blockchain_id>/', views.create_blockchain_portfolio,
         name='create_blockchain_portfolio'),
    path('change_portfolio/<int:blockchain_id>/', views.change_blockchain_portfolio,
         name='change_blockchain_portfolio'),
    path('delete_portfolio/<int:blockchain_id>/', views.delete_blockchain_portfolio,
         name='delete_blockchain_portfolio'),
    path('data/<int:blockchain_id>/', views.get_blockchain_data, name='get_blockchain_data'),
    # path('all-data/<int:user_id>/', views.get_all_data, name='get_all_data'),
    path('blockchain_data_pdf/<int:blockchain_id>/', views.get_blockchain_data_pdf, name='get_blockchain_data_pdf'),
]

cmc/urls.py
from django.urls import path

from . import views

app_name = 'cmc'

urlpatterns = [
    path('detail/<slug:slug>/', views.detail, name='crypto_detail'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from cmc.views import index
from exchanger.views import send_XLSX_by_email, send_PDF_by_email

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),

    path('exchanger/', include('exchanger.urls', namespace='exchanger')),
    path('blockchain/', include('blockchain.urls', namespace='blockchain')),

    path('cmc/', include('cmc.urls', namespace='cmc')),

    path('send_XLSX_by_email/<str:portfolio>/', send_XLSX_by_email, name='send_XLSX_by_email'),
    path('send_XLSX_by_email/<path:path_to_file>/', send_XLSX_by_email, name='send_XLSX_by_email'),
    path('send_PDF_by_email/<int:user_id>/', send_PDF_by_email, name='send_PDF_by_email'),
    path('send_PDF_by_email/<int:user_id>/<str:portfolio>/', send_PDF_by_email, name='send_PDF_by_email'),

    path('', index, name='index'),
    re_path('', include('social_django.urls', namespace='social'))

]

from account.api.urls import urlpatterns as users_urlpatterns
from blockchain.api.urls import urlpatterns as blockchain_urlpatterns
from exchanger.api.urls import urlpatterns as exchanger_urlpatterns

urlpatterns += [*users_urlpatterns, *blockchain_urlpatterns, *exchanger_urlpatterns]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

exchanger/urls.py
from django.urls import path

from . import views

app_name = 'exchanger'

urlpatterns = [
    path('detail/<slug:slug>/', views.detail, name='detail'),
    path('detail/<int:id>/<str:exchenger>/<slug:slug>/', views.detail, name='detail'),
    path('create_portfolio/<int:exchanger_id>/', views.create_portfolio, name='create_portfolio'),
    path('change_portfolio/<int:exchanger_id>/', views.change_portfolio, name='change_portfolio'),
    path('delete_portfolio/<int:exchanger_id>/', views.delete_portfolio, name='delete_portfolio'),
    path('data/<int:exchanger_id>/', views.get_exchanger_data, name='get_exchanger_data'),
    path('all-data/<int:user_id>/', views.get_all_data, name='get_all_data'),
    path('all_data_pdf/<int:user_id>/', views.get_all_data_pdf, name='get_all_data_pdf'),
    path('exchanger_data_pdf/<int:exchanger_id>/', views.get_exchanger_data_pdf, name='get_exchanger_data_pdf'),
    path('', views.exchangers, name='exchangers'),

]

cmc/models.py
from django.core.validators import validate_image_file_extension
from django.db import models
from django.urls import reverse

from passlib.hash import pbkdf2_sha256


class Cryptocurrency(models.Model):
    symbol = models.CharField(max_length=255, verbose_name='Symbol')
    name = models.CharField(max_length=255, verbose_name='Name')
    slug = models.SlugField(max_length=250, unique=True)
    website = models.URLField(max_length=200,
                              verbose_name='Site',
                              blank=True,
                              )

    contract = models.CharField(max_length=255, verbose_name='Contract', blank=True)
    description = models.TextField(verbose_name='Description', blank=True)
    logo = models.ImageField(upload_to=f'cryptocurrency/%Y/%m/%d/',
                             blank=True,
                             validators=[validate_image_file_extension])

    class Meta:
        indexes = [
            models.Index(fields=['symbol']),
        ]
        ordering = ['name']

    def __str__(self):
        return f'{self.name}. {self.symbol}'

    def get_absolute_url(self):
        return reverse('cmc:crypto_detail',
                       args=[self.slug])


class TelegramBot(models.Model):
    bot_name = models.CharField(max_length=255,
                                unique=True,
                                verbose_name='bot_name',
                                help_text="Bot name from telegram bot settings.")
    username = models.CharField(max_length=255,
                                unique=True,
                                verbose_name='username',
                                help_text="Bot username from telegram bot settings.", )
    bot_token = models.CharField(max_length=255,
                                 unique=True,
                                 verbose_name='bot_token',
                                 help_text="Bot token from telegram bot settings.", )
    chat_id = models.IntegerField(unique=True,
                                  verbose_name='chat_id',
                                  help_text="Bot id.", )
    hash_password = models.CharField(max_length=255,
                                     unique=True, )

    class Meta:
        indexes = [
            models.Index(fields=['bot_name']),
        ]
        ordering = ['bot_name']

    def __str__(self):
        return f'{self.bot_name}.'

    def save(self, *args, **kwargs):
        self.hash_password = pbkdf2_sha256.hash(f'{self.bot_name} + {self.username} + {self.chat_id}')
        super().save(*args, **kwargs)


def pwd_verify(*args, **kwargs):
    bot_name, username, chat_id = args
    hash_password = TelegramBot.objects.first().hash_password
    return bool(pbkdf2_sha256.verify(f'{bot_name} + {username} + {chat_id}',
                                     hash_password))

cmc/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, HttpResponse, get_object_or_404

from django import forms

from cmc.models import Cryptocurrency
from exchanger.handlers import get_paginator

PAGINATOR_QTY = 10


def index(request):

    cryptocurrencies_list = Cryptocurrency.objects.all().order_by('id')[:154]
    cryptocurrencies, page_range = get_paginator(request, cryptocurrencies_list)
    return render(request,
                  'cmc/cmc/index.html',
                  {'cryptocurrencies': cryptocurrencies,
                   'page_range': page_range}
                  )


def detail(request, slug):
    crypto = get_object_or_404(Cryptocurrency,
                               slug=slug
                               )

    return render(request, 'cmc/cmc/detail.html',
                  {'crypto': crypto}
                  )

cmc/templates/base.html
<!DOCTYPE html>
{% load django_bootstrap5 %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% load exchanger_tags %}
{% load blockchain_tags %}


{% load static %}

<html lang="{{ LANGUAGE_CODE|default:'en_us' }}">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Page title -->
    <title>{% block bootstrap5_title %}django-bootstrap5 template title{% endblock %}</title>

    <!-- Bootstrap CSS -->
    {% bootstrap_css %}


    <!-- Bootstrap JavaScript if it is in head -->
    {% if 'javascript_in_head'|bootstrap_setting %}
        {% bootstrap_javascript %}
    {% endif %}

    <link rel="stylesheet" href="{% static 'cmc/css/cmc.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'cmc/css/my_css.css' %}" type="text/css">

    {% block bootstrap5_extra_head %}{% endblock %}

</head>

<body>
    {% get_exchanger_portfolios user as exchanger_portfolios %}
    {% get_blockchain_portfolios user as blockchain_portfolios %}
    {% get_path_to_users_xlsx_file_all user as path_to_users_xlsx_file_all %}

{% include 'include/navbar.html' %}

<main role="main">
    <div class="height100 container-fluid my_jumbotron">

        {% block bootstrap5_content %} CONTENT {% endblock %}


        <!-- Bootstrap JavaScript if it is in body -->
        {% if not 'javascript_in_head'|bootstrap_setting %}
            {% bootstrap_javascript %}
        {% endif %}


        {% block bootstrap5_extra_script %}{% endblock %}

{#        {% include 'include/_go_back.html' %}#}
    </div>
</main>

{% include 'include/footer.html' %}
</body>
</html>

cmc/templates/base_index.html
{% extends "base.html" %}
{% load exchanger_tags %}
{% load blockchain_tags %}

{% block bootstrap5_content %}

    <div class="height100 main">

        <div class="main_content">
            {% include 'include/_message.html' %}

            {% block main_content %}
            {% endblock main_content %}
        </div>

        <aside class="sidebar">

            {% if user.is_staff %}
                <div class="container">
                    <ul>
                        <li>Total coins on site: {% total_coins %}</li>
                        <li>Total users on site: {% total_users %}</li>
                        <li>Total exchanger portfolio on site: {% total_exchanger_portfolios %}</li>
                        <li>Total blockchain portfolio on site: {% total_blockchain_portfolios %}</li>
                    </ul>
                </div>
            {% endif %}

            <div class="container">
                {% if user.is_authenticated %}

                    <h2 class="text-center">{{ user }}.</h2>

                    <div class="row">
                        <div class="col">
                            <h5> Exchangers:</h5>
                            {% if exchanger_portfolios %}
                                {% for exchanger_portfolio in exchanger_portfolios %}

                                    <div class="dropdown dropend">

                                        <a type="button" class="nav-link dropdown-toggle custom"
                                           data-bs-toggle="dropdown"
                                           href="#">
                                            {{ exchanger_portfolio }}
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="{% url "exchanger:get_exchanger_data" exchanger_portfolio.id %}"
                                                   class="dropdown-item link">data</a>
                                            </li>

                                            <hr class="dropdown-divider">
                                            <li>
                                                <a href="{% get_path_to_users_xlsx_file_one user exchanger_portfolio %}"
                                                   class="dropdown-item link"
                                                   download>XLSX Save</a></li>
                                            <li>
                                            </li>
                                            <li><a class="dropdown-item link"
                                                   href="{% url "send_XLSX_by_email" portfolio=exchanger_portfolio %}">XLSX
                                                to Email</a>
                                            </li>

                                            <hr class="dropdown-divider">
                                            <li>
                                                <a href="{% url "exchanger:get_exchanger_data_pdf" exchanger_portfolio.id %}"
                                                   class="dropdown-item link" target="_blank">PDF Save</a>
                                            <li>
                                            </li>
                                            <li><a class="dropdown-item link"
                                                   href="{% url "send_PDF_by_email" user_id=user.id portfolio=exchanger_portfolio %}">PDF
                                                to Email</a>
                                            </li>
                                        </ul>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <p>You did not create yet.</p>
                            {% endif %}
                        </div>

                        <div class="col">
                            <h5>Blockchains:</h5>
                            {% if blockchain_portfolios %}
                                {% for blockchain_portfolio in blockchain_portfolios %}

                                    <div class="dropdown dropend">

                                        <a type="button" class="nav-link dropdown-toggle custom"
                                           data-bs-toggle="dropdown"
                                           href="#">
                                            {{ blockchain_portfolio }}
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="{% url "blockchain:get_blockchain_data" blockchain_portfolio.id %}"
                                                   class="dropdown-item link">data</a>
                                            </li>

                                            <hr class="dropdown-divider">
                                            <li><a href="{{ path_to_users_xlsx_file_all }}" class="dropdown-item link"
                                                   download>XLSX Save</a></li>
                                            <li>
                                                <hr class="dropdown-divider">
                                            </li>
                                            <li><a class="dropdown-item link"
                                                   href="{% url "send_XLSX_by_email" path_to_file=path_to_users_xlsx_file_all %}">XLSX
                                                to Email</a>
                                            </li>

                                            <hr class="dropdown-divider">
                                            <li>
                                                <a href="{% url "blockchain:get_blockchain_data_pdf" blockchain_portfolio.id %}"
                                                   class="dropdown-item link" target="_blank">PDF Save</a>
                                            <li>
                                                <hr class="dropdown-divider">
                                            </li>
                                            <li><a class="dropdown-item link"
                                                   href="{% url "send_PDF_by_email" user_id=user.id portfolio=blockchain_portfolio %}">PDF
                                                to Email</a>
                                            </li>
                                        </ul>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <p>You did not create yet.</p>
                            {% endif %}
                        </div>
                    </div>

                    {% if blockchain_portfolios or exchanger_portfolios %}
                        <div class="dropdown container d-flex align-items-center justify-content-center">

                            <button type="button" class="btn btn-success btn-sm dropdown-toggle"
                                    data-bs-toggle="dropdown">ALL PORTFOLIOS</button>

                            <ul class="dropdown-menu">
                                <li><a href="{% url "exchanger:get_all_data" user.id %}" class="dropdown-item link">
                                    Get data for all portfolios</a>
                                </li>
                                <hr class="dropdown-divider">

                                <li><a href="{{ path_to_users_xlsx_file_all }}" class="dropdown-item link"
                                       download>XLSX Save</a></li>
                                <li><a class="dropdown-item link"
                                       href="{% url "send_XLSX_by_email" path_to_file=path_to_users_xlsx_file_all %}">XLSX
                                    to Email</a>
                                </li>
                                <hr class="dropdown-divider">

                                <li><a href="{% url "exchanger:get_all_data_pdf" user.id %}"
                                       class="dropdown-item link" target="_blank">PDF save</a>
                                <li><a class="dropdown-item link"
                                       href="{% url "send_PDF_by_email" user_id=user.id %}">PDF to Email</a></li>
                            </ul>
                        </div>
                    {% endif %}
                {% endif %}
            </div>

            {% block sidebar %}{% endblock sidebar %}

        </aside>
    </div>

{% endblock %}